"""Prometheus metrics definitions for the Hydra trading platform.

All metric objects are created lazily on first access so that importing
this module does **not** pull in ``prometheus_client`` at import time.
Helper functions provide a clean API for the rest of the codebase.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from prometheus_client import Counter, Gauge, Histogram

# ---------------------------------------------------------------------------
# Lazy singleton registry
# ---------------------------------------------------------------------------

_metrics: dict[str, Any] = {}
_initialized: bool = False


def _ensure_initialized() -> None:
    """Create all Prometheus collectors on first call."""
    global _initialized
    if _initialized:
        return

    from prometheus_client import Counter, Gauge, Histogram

    # -- Trading metrics ----------------------------------------------------

    _metrics["trades_total"] = Counter(
        "hydra_trades_total",
        "Total number of executed trades",
        labelnames=["symbol", "side", "strategy_id", "exchange_id"],
    )

    _metrics["trade_pnl"] = Histogram(
        "hydra_trade_pnl",
        "PnL distribution per trade",
        labelnames=["symbol", "strategy_id"],
        buckets=(-500, -200, -100, -50, -20, -10, 0, 10, 20, 50, 100, 200, 500, 1000),
    )

    _metrics["position_size"] = Gauge(
        "hydra_position_size",
        "Current position size by symbol and exchange",
        labelnames=["symbol", "exchange_id"],
    )

    _metrics["portfolio_value"] = Gauge(
        "hydra_portfolio_value",
        "Total portfolio value in USDT",
    )

    _metrics["drawdown_pct"] = Gauge(
        "hydra_drawdown_pct",
        "Current drawdown as a percentage from peak equity",
    )

    _metrics["daily_pnl"] = Gauge(
        "hydra_daily_pnl",
        "Realized + unrealized PnL for the current day in USDT",
    )

    _metrics["signal_count"] = Counter(
        "hydra_signal_count",
        "Number of signals generated by strategy",
        labelnames=["strategy_id", "signal_type"],
    )

    # -- System metrics -----------------------------------------------------

    _metrics["event_bus_latency"] = Histogram(
        "hydra_event_bus_latency_seconds",
        "End-to-end latency of event bus message delivery",
        buckets=(0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0),
    )

    _metrics["exchange_api_latency"] = Histogram(
        "hydra_exchange_api_latency_seconds",
        "Latency of outbound exchange REST API calls",
        labelnames=["exchange_id", "endpoint"],
        buckets=(0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0),
    )

    _metrics["ws_reconnects"] = Counter(
        "hydra_ws_reconnects_total",
        "Number of WebSocket reconnections per exchange",
        labelnames=["exchange_id"],
    )

    _metrics["order_fill_latency"] = Histogram(
        "hydra_order_fill_latency_seconds",
        "Time from order submission to fill confirmation",
        buckets=(0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0),
    )

    _metrics["ml_inference_latency"] = Histogram(
        "hydra_ml_inference_latency_seconds",
        "Latency of ML model inference",
        labelnames=["model_name"],
        buckets=(0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5),
    )

    _metrics["data_gap"] = Gauge(
        "hydra_data_gap_seconds",
        "Seconds since last received market data update",
        labelnames=["exchange_id", "symbol"],
    )

    _metrics["reconciliation_mismatch"] = Gauge(
        "hydra_reconciliation_mismatch",
        "Non-zero when local and exchange positions diverge (1 = mismatch)",
        labelnames=["exchange_id", "symbol"],
    )

    _initialized = True


# ---------------------------------------------------------------------------
# Accessor helpers — each returns the typed collector
# ---------------------------------------------------------------------------


def get_trades_total() -> Counter:
    """Return the ``hydra_trades_total`` counter."""
    _ensure_initialized()
    return _metrics["trades_total"]


def get_trade_pnl() -> Histogram:
    """Return the ``hydra_trade_pnl`` histogram."""
    _ensure_initialized()
    return _metrics["trade_pnl"]


def get_position_size() -> Gauge:
    """Return the ``hydra_position_size`` gauge."""
    _ensure_initialized()
    return _metrics["position_size"]


def get_portfolio_value() -> Gauge:
    """Return the ``hydra_portfolio_value`` gauge."""
    _ensure_initialized()
    return _metrics["portfolio_value"]


def get_drawdown_pct() -> Gauge:
    """Return the ``hydra_drawdown_pct`` gauge."""
    _ensure_initialized()
    return _metrics["drawdown_pct"]


def get_daily_pnl() -> Gauge:
    """Return the ``hydra_daily_pnl`` gauge."""
    _ensure_initialized()
    return _metrics["daily_pnl"]


def get_signal_count() -> Counter:
    """Return the ``hydra_signal_count`` counter."""
    _ensure_initialized()
    return _metrics["signal_count"]


def get_event_bus_latency() -> Histogram:
    """Return the ``hydra_event_bus_latency_seconds`` histogram."""
    _ensure_initialized()
    return _metrics["event_bus_latency"]


def get_exchange_api_latency() -> Histogram:
    """Return the ``hydra_exchange_api_latency_seconds`` histogram."""
    _ensure_initialized()
    return _metrics["exchange_api_latency"]


def get_ws_reconnects() -> Counter:
    """Return the ``hydra_ws_reconnects_total`` counter."""
    _ensure_initialized()
    return _metrics["ws_reconnects"]


def get_order_fill_latency() -> Histogram:
    """Return the ``hydra_order_fill_latency_seconds`` histogram."""
    _ensure_initialized()
    return _metrics["order_fill_latency"]


def get_ml_inference_latency() -> Histogram:
    """Return the ``hydra_ml_inference_latency_seconds`` histogram."""
    _ensure_initialized()
    return _metrics["ml_inference_latency"]


def get_data_gap() -> Gauge:
    """Return the ``hydra_data_gap_seconds`` gauge."""
    _ensure_initialized()
    return _metrics["data_gap"]


def get_reconciliation_mismatch() -> Gauge:
    """Return the ``hydra_reconciliation_mismatch`` gauge."""
    _ensure_initialized()
    return _metrics["reconciliation_mismatch"]


# ---------------------------------------------------------------------------
# Convenience update helpers
# ---------------------------------------------------------------------------


def record_trade(
    symbol: str,
    side: str,
    strategy_id: str,
    exchange_id: str,
    pnl: float | None = None,
) -> None:
    """Increment trade counter and optionally record PnL."""
    get_trades_total().labels(
        symbol=symbol,
        side=side,
        strategy_id=strategy_id,
        exchange_id=exchange_id,
    ).inc()
    if pnl is not None:
        get_trade_pnl().labels(symbol=symbol, strategy_id=strategy_id).observe(pnl)


def update_position(symbol: str, exchange_id: str, size: float) -> None:
    """Set current position size for a symbol/exchange pair."""
    get_position_size().labels(symbol=symbol, exchange_id=exchange_id).set(size)


def update_portfolio(value: float, drawdown_pct: float, daily_pnl: float) -> None:
    """Update portfolio-level gauges."""
    get_portfolio_value().set(value)
    get_drawdown_pct().set(drawdown_pct)
    get_daily_pnl().set(daily_pnl)


def record_signal(strategy_id: str, signal_type: str) -> None:
    """Increment signal counter."""
    get_signal_count().labels(strategy_id=strategy_id, signal_type=signal_type).inc()


def observe_event_bus_latency(seconds: float) -> None:
    """Record event bus message delivery latency."""
    get_event_bus_latency().observe(seconds)


def observe_exchange_api_latency(
    exchange_id: str,
    endpoint: str,
    seconds: float,
) -> None:
    """Record exchange API call latency."""
    get_exchange_api_latency().labels(
        exchange_id=exchange_id,
        endpoint=endpoint,
    ).observe(seconds)


def record_ws_reconnect(exchange_id: str) -> None:
    """Increment WebSocket reconnection counter for an exchange."""
    get_ws_reconnects().labels(exchange_id=exchange_id).inc()


def observe_order_fill_latency(seconds: float) -> None:
    """Record order fill latency."""
    get_order_fill_latency().observe(seconds)


def observe_ml_inference_latency(model_name: str, seconds: float) -> None:
    """Record ML model inference latency."""
    get_ml_inference_latency().labels(model_name=model_name).observe(seconds)


def update_data_gap(exchange_id: str, symbol: str, gap_seconds: float) -> None:
    """Set the current data gap for an exchange/symbol pair."""
    get_data_gap().labels(exchange_id=exchange_id, symbol=symbol).set(gap_seconds)


def update_reconciliation(
    exchange_id: str,
    symbol: str,
    mismatch: bool,
) -> None:
    """Set reconciliation mismatch status (1 = mismatch, 0 = ok)."""
    get_reconciliation_mismatch().labels(
        exchange_id=exchange_id,
        symbol=symbol,
    ).set(1.0 if mismatch else 0.0)


# ---------------------------------------------------------------------------
# Registry reset — used only in tests
# ---------------------------------------------------------------------------


def _reset_metrics() -> None:
    """Clear all metric collectors. For test isolation only."""
    global _initialized

    if not _initialized:
        return

    import contextlib

    from prometheus_client import REGISTRY

    for key in list(_metrics.keys()):
        with contextlib.suppress(Exception):
            REGISTRY.unregister(_metrics[key])
    _metrics.clear()
    _initialized = False
