'use client';

import { Globe, Bell, Cog, CheckCircle, XCircle } from 'lucide-react';
import { DataCard } from '@/components/ui/DataCard';
import { Input } from '@/components/ui/Input';
import { Select } from '@/components/ui/Select';
import { Button } from '@/components/ui/Button';
import { cn } from '@/components/ui/cn';

/* ---------- Exchange data ---------- */

interface Exchange {
  id: string;
  name: string;
  logo: string;
  connected: boolean;
  apiKeySet: boolean;
  lastSync: string;
}

const exchanges: Exchange[] = [
  { id: 'binance', name: 'Binance', logo: 'B', connected: true, apiKeySet: true, lastSync: '2 min ago' },
  { id: 'bybit', name: 'Bybit', logo: 'BY', connected: true, apiKeySet: true, lastSync: '5 min ago' },
  { id: 'kraken', name: 'Kraken', logo: 'K', connected: false, apiKeySet: false, lastSync: 'Never' },
  { id: 'okx', name: 'OKX', logo: 'O', connected: false, apiKeySet: true, lastSync: '3 days ago' },
];

/* ---------- Page ---------- */

export default function SettingsPage() {
  return (
    <div className="flex flex-col gap-6">
      {/* Exchange connections */}
      <DataCard title="Exchange Connections" description="Manage your exchange API connections">
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          {exchanges.map((exchange) => (
            <div
              key={exchange.id}
              className={cn(
                'rounded-xl border p-4 transition-colors',
                exchange.connected
                  ? 'border-status-success/30 bg-status-success/5'
                  : 'border-border-default bg-bg-secondary',
              )}
            >
              <div className="flex items-start justify-between">
                <div className="flex items-center gap-3">
                  <div
                    className={cn(
                      'flex h-10 w-10 items-center justify-center rounded-lg text-sm font-bold',
                      exchange.connected
                        ? 'bg-status-success/20 text-status-success'
                        : 'bg-bg-tertiary text-text-muted',
                    )}
                  >
                    {exchange.logo}
                  </div>
                  <div>
                    <h4 className="text-sm font-semibold text-text-primary">
                      {exchange.name}
                    </h4>
                    <p className="mt-0.5 text-xs text-text-muted">
                      Last sync: {exchange.lastSync}
                    </p>
                  </div>
                </div>
                {exchange.connected ? (
                  <CheckCircle className="h-5 w-5 text-status-success" aria-label="Connected" />
                ) : (
                  <XCircle className="h-5 w-5 text-text-light" aria-label="Disconnected" />
                )}
              </div>
              <div className="mt-3 flex items-center justify-between">
                <span className="text-xs text-text-muted">
                  API Key: {exchange.apiKeySet ? 'Configured' : 'Not set'}
                </span>
                <Button variant={exchange.connected ? 'ghost' : 'outline'} size="sm">
                  {exchange.connected ? 'Manage' : 'Connect'}
                </Button>
              </div>
            </div>
          ))}
        </div>
      </DataCard>

      {/* Notification preferences */}
      <DataCard title="Notification Preferences" description="Configure alert and notification settings">
        <div className="space-y-4">
          {[
            { label: 'Trade Executions', description: 'Notify when trades are filled', enabled: true },
            { label: 'Risk Alerts', description: 'Circuit breaker and drawdown warnings', enabled: true },
            { label: 'Model Drift', description: 'Alert when model drift exceeds threshold', enabled: true },
            { label: 'Strategy Signals', description: 'New signal generated by strategies', enabled: false },
            { label: 'System Health', description: 'Service outages and connectivity issues', enabled: true },
          ].map((pref) => (
            <div
              key={pref.label}
              className="flex items-center justify-between rounded-lg border border-border-default bg-bg-secondary p-3"
            >
              <div className="flex items-center gap-3">
                <Bell className="h-4 w-4 text-text-muted shrink-0" aria-hidden="true" />
                <div>
                  <p className="text-sm font-medium text-text-primary">{pref.label}</p>
                  <p className="text-xs text-text-muted">{pref.description}</p>
                </div>
              </div>
              <div
                className={cn(
                  'relative h-6 w-11 cursor-pointer rounded-full transition-colors',
                  pref.enabled ? 'bg-accent-primary' : 'bg-bg-active',
                )}
                role="switch"
                aria-checked={pref.enabled}
                aria-label={`${pref.enabled ? 'Disable' : 'Enable'} ${pref.label}`}
                tabIndex={0}
              >
                <div
                  className={cn(
                    'absolute top-1 h-4 w-4 rounded-full bg-white shadow transition-transform',
                    pref.enabled ? 'translate-x-[22px]' : 'translate-x-1',
                  )}
                />
              </div>
            </div>
          ))}
        </div>
      </DataCard>

      {/* Platform config */}
      <DataCard title="Platform Configuration" description="General platform settings">
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          <Select
            label="Default Trading Pair"
            options={[
              { value: 'btcusdt', label: 'BTC/USDT' },
              { value: 'ethusdt', label: 'ETH/USDT' },
              { value: 'btcusd', label: 'BTC/USD' },
            ]}
            defaultValue="btcusdt"
          />
          <Select
            label="Default Timeframe"
            options={[
              { value: '1m', label: '1 Minute' },
              { value: '5m', label: '5 Minutes' },
              { value: '15m', label: '15 Minutes' },
              { value: '1h', label: '1 Hour' },
              { value: '4h', label: '4 Hours' },
            ]}
            defaultValue="1h"
          />
          <Select
            label="Trading Mode"
            options={[
              { value: 'paper', label: 'Paper Trading' },
              { value: 'testnet', label: 'Testnet' },
              { value: 'live', label: 'Live Trading' },
            ]}
            defaultValue="paper"
            hint="Paper trading mode is recommended for testing"
          />
          <Input
            label="Max Concurrent Strategies"
            type="number"
            defaultValue="5"
            hint="Maximum number of strategies running simultaneously"
          />
        </div>
        <div className="mt-4 flex justify-end">
          <Button variant="primary">
            <Cog className="h-4 w-4" />
            Save Configuration
          </Button>
        </div>
      </DataCard>
    </div>
  );
}
